### PR TITLE
New schema: stimulus presentation trial

### PR DESCRIPTION
**Pull request by jonahweissman**
Here is a pretty rough draft of a schema for stimulus presentation trials. I'm looking for a little feedback about how much detail you want the human readable spec to go into (what's there right now is mostly a placeholder), as well as whether there are any other keys that might be appropriate to include (perhaps stimulus_end?).

This PR also includes switching the automatic validation to be a pytest plugin, and changing the way a schemas are recognized from codeblocks. It shouldn't have any impact on the functionality, but hopefully it'll be a little easier to track down validation bugs.

### CODE REVIEW

**Comment by dmeliza** [comment]
I'm happy to fill in some of the rationale in the human-readable spec once we finalize it.

There would seem to be a lot of different ways of encoding stimulus information. For the sake of backwards compatibility, perhaps we should use whatever is most common in our data? I think this is `stimulus`, `stim_on`, and `stim_off`.

The main alternatives I can think of would be to have stimulus be a single, dictionary-valued field (with "name", "on", and "off" keys); or to make the stimulus interval a 2-element array like the `interval` key.

We might make `stim_off` optional to more succinctly represent instantaneous stimuli, but in point of fact everything has duration so I don't think it's worth the minor savings we might attain.

**Comment by jonahweissman** [comment]
I've updated the spec to match the way we were discussing it today (no top level URI scheme, stimulus contains `name` and `interval`). If it looks right, then I think we still need to:
- [ ] write up human readable spec
- [ ] figure out a plan for migrating existing pprox files to comply

**Comment by dmeliza** [comment]
Looks good. You can go ahead and finalize the PR. I'll merge it and then work on the human-readable spec. We'll have to come up with a migration plan separately - we should probably start a pprox project as a home for CLI tools and plugins.

**Comment by dmeliza** [comment]
Never mind, looks like I can finalize from my end - merging now.

**Pull request merged**
