### PR TITLE
Specifying the beginning and end of a process

### PR DESCRIPTION
**Pull request by jonahweissman**
Pretty straightforward changes: `proc_off` is now mandatory because we want to be able to distinguish between a lack of events and a lack of data.  `proc_on` is optional because it can be assumed to have a value of zero. I updated the examples accordingly.

If this gets merged, a lot of previously valid pprox files suddenly become non-compliant with the spec, so this will definitely require bumping the version number, and also possibly figuring out a way to include the version number in the `$schema` field to allow consumers of the spec to have different logic for backwards compatibility.

This is based on #1, so merging needs to wait for that.

### CODE REVIEW

**Comment by dmeliza** [comment]
Overall, this is a great idea that addresses a major issue with the spec (and with point process data in general). The implementation is probably fine as is, but let's discuss a few things before finalizing anything.

1. Naming. "on" and "off" seem a little opaque. What about "begin" and "end"?
2. Naming pt 2. What do you think about "interval" as in observation interval instead of "proc"?
3. Backwards compatibility. It seems like we could make both proc_on/begin and proc_off/end optional to maintain backwards compatibility. If the field is absent, then it means that information about the observation interval is not available. On a related note, there are some cases where there are negative event times (e.g. when spikes come before the onset of a stimulus), so perhaps the meaning of a missing `proc_on` field should be "not available" too...
4. Does it make sense to combine into a single field with a value that's an array of two numbers? If missing = not available, then the implication is that both fields should be present or absent.

**Comment by jonahweissman** [comment]
>    1. Naming. "on" and "off" seem a little opaque. What about "begin" and "end"?
>    2. Naming pt 2. What do you think about "interval" as in observation interval instead of "proc"?
>    4. Does it make sense to combine into a single field with a value that's an array of two numbers? If missing = not available, then the implication is that both fields should be present or absent.
>
>    On a related note, there are some cases where there are negative event times (e.g. when spikes come before the onset of a stimulus), so perhaps the meaning of a missing `proc_on` field should be "not available" too...

I completely agree. I think an `interval` key that contains a length 2 array would be really clean. Requiring both the beginning and end of the interval to be present seems very reasonable; omitting the start of the interval if it's zero is not worth the loss of clarity.  

>     3. Backwards compatibility. It seems like we could make both proc_on/begin and proc_off/end optional to maintain backwards compatibility. If the field is absent, then it means that information about the observation interval is not available. 

I think my hesitation with this is that a point process without information about the interval is extremely hard to interpret. My understanding is that the beginning and end of a recording of a point process will always be known, so it wouldn't be unreasonable to ask pprox creators to include that information. I'm worried that if we make it optional, future creators of pprox files will not use it, which would create problems for them later.

No matter what we do, we'll have to deal with the fact that we have some pprox files that are missing interval information. If we start hosting the pprox spec at `https://meliza.org/spec:2/v2.0/pprox.json` and make new pprox comply with the latest version of the spec at the time it is created, with a $schema pointing to the appropriate version, we can ensure that consumers of pprox files will always know when they are dealing with data that has missing interval data.

**Comment by dmeliza** [comment]
I see your point about backwards compatibility and versioning. Consumer scripts are going to have to deal with the there being 1.0 and 2.0 pprox files in our data archives (unless we do some kind of organized migration), so it's probably better for them to check the spec version rather than look for the key (and deal with the possibility that someone might use `interval` as a key in a 1.0 file but mean something different).

Does jsonschema specify some kind of `$version` key that can be used instead of the spec URI? Might be easier for consumers to check that instead of having to parse the URI...

So I think once you change from `proc_on` and `proc_off` to `interval` we are good to go on this PR.

**Comment by jonahweissman** [comment]
> Does jsonschema specify some kind of `$version` key that can be used instead of the spec URI? Might be easier for consumers to check that instead of having to parse the URI...

It doesn't look like it. I think instead of parsing the version string from the URI, consumers could just compare the entire $schema key against the URI of the schema that their code is designed to handle. It's definitely a little clunky, but it ensures that consumers are getting exactly what they expect.

> So I think once you change from `proc_on` and `proc_off` to `interval` we are good to go on this PR.

Done.

**Pull request merged**
